version: '3'

services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: odoo17
      POSTGRES_USER: odoo17
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # Odoo 17 service
  odoo17:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    depends_on:
      - postgres
    volumes:
      - odoo_data:/opt/odoo17

volumes:
  postgres_data:
  odoo_data:
